version: "3.7"

networks:
  internal:
    driver: bridge

  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - internal
      - app-network

  php-fpm:
    image: php-base:latest
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - app-network
