version: "3.7"

networks:
  internal:
    driver: bridge

  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - internal
      - app-network

  php-fpm:
    image: php-dev:latest
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  
  mysql:
    image: mysql:8.0-debian
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:7.2
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local